language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir cmake-build
  - cd cmake-build
script: cmake -DOCE_ENABLE_DEB_FLAG:BOOL=OFF
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DOCE_TESTING:BOOL=ON
        -DOCE_VISUALISATION:BOOL=OFF
        -DOCE_OCAF:BOOL=ON
        -DOCE_DATAEXCHANGE:BOOL=ON
        -DOCE_DISABLE_X11:BOOL=ON
        -DOCE_USE_PCH:BOOL=ON
        .. && echo "" &&
        if test -x /usr/bin/getconf; then echo "Starting build with -j$(/usr/bin/getconf _NPROCESSORS_ONLN) ...";
        make -j$(/usr/bin/getconf _NPROCESSORS_ONLN); else make; fi
after_script: make test
